---
- name: test frstudent module
  gather_facts: false
  hosts: localhost
  tasks:
  - name: run my new module
    netology.frstudent.fr_module:
#    fr_module:
      path: "/home/devops/ansible/src/like_pass"
      context: "Oppps, I meamd contetn but use context. Again"
      overwrite: False
    register: output
  - name: Show output
    debug:
      msg: "{{ output }}"
